defaults:
  lookback_days: 30
  base_timeframe: "5m"
  universe_symbol: "^NDX"
  universe_cache_hours: 12
  websocket_reconnect_delay: 5
  max_reconnect_attempts: 10
  backfill_batch_size: 50
  backfill_delay_seconds: 0.1

trading:
  session_start_hour: 9  # 9:30 AM EST (market open)
  session_start_minute: 30
  session_end_hour: 16    # 4:00 PM EST (market close)
  session_end_minute: 0

indicators:
  ema_fast: 9
  ema_slow: 21
  rsi_period: 14
  bb_period: 20
  bb_std: 2.0
  rsi_overbought: 70
  rsi_oversold: 30

signals:
  long_trigger:
    ema_cross_above: true
    rsi_min: 50
    price_above_vwap: true
    min_rvol: 2.0